# Generated by Django 5.1.4 on 2025-09-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='steam_id',
        ),
        migrations.AddField(
            model_name='player',
            name='user_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
