# Generated by Django 5.1.4 on 2025-09-19 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_player_steam_id_player_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(max_length=20)),
                ('target_ip', models.CharField(max_length=15)),
                ('issuer_id', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=100)),
                ('is_bought', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.server')),
            ],
        ),
    ]
