# Generated by Django 5.1.4 on 2025-09-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='target_ip',
        ),
        migrations.AddField(
            model_name='ban',
            name='ban_type',
            field=models.CharField(choices=[('id', 'id'), ('ip', 'ip')], default='id', max_length=2),
        ),
    ]
