# Generated by Django 5.1.4 on 2025-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_ban_target_ip_ban_ban_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='ban_type',
        ),
        migrations.AddField(
            model_name='ban',
            name='target_ip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ban',
            name='target_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
