# Generated by Django 5.2.7 on 2025-12-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ban_ban_type_ban_target_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
