# Generated by Django 5.2.9 on 2025-12-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_server_server_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='scpsl_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_id',
            field=models.IntegerField(default=0),
        ),
    ]
