# Generated by Django 5.2.9 on 2026-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_server_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPunishment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_id', models.CharField(max_length=32)),
                ('issuer_id', models.CharField(max_length=32)),
                ('server_id', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('ban', 'Ban'), ('mute', 'Mute')], max_length=4)),
                ('reason', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('is_buyable', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'player_punishment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerXP',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('server_id', models.PositiveSmallIntegerField()),
                ('nickname', models.CharField(max_length=64)),
                ('current_xp', models.PositiveSmallIntegerField(default=0)),
                ('lvl', models.PositiveSmallIntegerField(default=0)),
                ('coins', models.PositiveSmallIntegerField(default=0)),
                ('first_activity', models.DateTimeField()),
                ('last_activity', models.DateTimeField()),
                ('total_rounds', models.PositiveSmallIntegerField(default=0)),
                ('total_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'player_xp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PunishmentHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('punishment_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('extended', 'Extended'), ('reduced', 'Reduced'), ('revoked', 'Revoked'), ('reapplied', 'Reapplied')], max_length=9)),
                ('old_expires_at', models.DateTimeField(blank=True, null=True)),
                ('new_expires_at', models.DateTimeField(blank=True, null=True)),
                ('issuer_id', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'punishment_history',
                'managed': False,
            },
        ),
    ]
