# Generated by Django 5.2.9 on 2026-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_playerpunishment_playerxp_punishmenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_admin_black_list',
        ),
        migrations.AddField(
            model_name='player',
            name='prefix',
            field=models.CharField(default='', max_length=20),
        ),
    ]
