# Generated by Django 5.2.9 on 2026-05-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_player_is_admin_black_list_player_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
